XCODE_USER_TEMPLATES_DIR=~/Library/Developer/Xcode/Templates/File\ Templates
VIPER_TEMPLATES_DIR=Templates/Viper\ Module.xctemplate
VIPER_REMOVE_TEMPLATES_PATH=Viper\ Module.xctemplate

SWIFTUI_VIPER_TEMPLATES_DIR=Templates/SwiftUI\ VIPER\ Module.xctemplate
SWIFTUI_VIPER_REMOVE_TEMPLATES_PATH=SwiftUI\ VIPER\ Module.xctemplate

install_templates:
	rm -R -f $(XCODE_USER_TEMPLATES_DIR)/$(VIPER_TEMPLATES_DIR)
	mkdir -p $(XCODE_USER_TEMPLATES_DIR)
	cp -R -f $(VIPER_TEMPLATES_DIR) $(XCODE_USER_TEMPLATES_DIR)

uninstall_templates:
	rm -R $(XCODE_USER_TEMPLATES_DIR)/$(VIPER_REMOVE_TEMPLATES_PATH)
	rm -R $(XCODE_USER_TEMPLATES_DIR)/$(SWIFTUI_VIPER_REMOVE_TEMPLATES_PATH)
	
install_swiftui_viper_templates:
	rm -R -f $(XCODE_USER_TEMPLATES_DIR)/$(SWIFTUI_VIPER_TEMPLATES_DIR)
	mkdir -p $(XCODE_USER_TEMPLATES_DIR)
	cp -R -f $(SWIFTUI_VIPER_TEMPLATES_DIR) $(XCODE_USER_TEMPLATES_DIR)

